[package]
name = "testilu"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.15", features=["jpeg"]}
bevy_rapier3d = { version = "0.29.0", features = ["simd-stable", "debug-render-3d"]}
bevy_ui = "0.15.3"

[dependencies.gltf]
version = "1"

# Default binary is now src/main.rs