[package]
name = "testilu"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.15", features=["jpeg"]}
avian3d = "0.2"
bevy_ui = "0.15.3"

[dependencies.gltf]
version = "1"

# Default binary is now src/main.rs